#!/bin/bash
category="indoor"

# Set prompt and scene folder paths
PROMPT_FOLDER="../prompt/$category"
SCENE_FOLDER="../generate_mvimages/results--20241101-000523"
OUTPUT_FOLDER="../generate_mvimages/results--20241101-000523"

# Create output folder
mkdir -p "$OUTPUT_FOLDER"

# Initialize an array to store all scene CLIP scores
declare -a CLIP_SCORES

# Loop through all prompt folders
for PROMPT_DIR in "$PROMPT_FOLDER"/*; do
    # Get the current prompt folder's name
    PROMPT_NAME=$(basename "$PROMPT_DIR")
    
    # Text file in the current prompt folder
    PROMPT_FILE="$PROMPT_DIR/$PROMPT_NAME.txt"
    
    # Corresponding scene folder path
    SCENE_SUBFOLDER="$SCENE_FOLDER/$PROMPT_NAME"
    
    # Check if scene folder exists
    if [ -d "$SCENE_SUBFOLDER" ]; then
        # Create corresponding output subfolder
        PROMPT_OUTPUT_FOLDER="$OUTPUT_FOLDER/$PROMPT_NAME"
        mkdir -p "$PROMPT_OUTPUT_FOLDER"

        echo "Processing prompt: $PROMPT_FILE with scene: $SCENE_SUBFOLDER"
        
        # Run CLIP_Score.py to process the current prompt and scene
        CUDA_VISIBLE_DEVICES=7 python CLIP_Score.py --input_folder "$SCENE_SUBFOLDER" --output_folder "$PROMPT_OUTPUT_FOLDER" --prompt_file "$PROMPT_FILE"
        
        echo "Finished processing prompt: $PROMPT_FILE for scene: $SCENE_SUBFOLDER"

        # Score file assumed to be generated by CLIP_Score.py
        SCORE_FILE="$PROMPT_OUTPUT_FOLDER/clip_scores.txt"
        if [ -f "$SCORE_FILE" ]; then
            # Extract Mean Score from the score file
            MEAN_SCORE=$(grep -oP '(?<=Mean Score: )[-+]?[0-9]*\.?[0-9]+' "$SCORE_FILE")
            if [[ "$MEAN_SCORE" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
                CLIP_SCORES+=("$MEAN_SCORE")
            else
                echo "Warning: Non-numeric score in $SCORE_FILE for prompt $PROMPT_NAME, skipping..."
            fi
        else
            echo "Score file not found for prompt: $PROMPT_NAME"
        fi
    else
        echo "Scene folder for prompt $PROMPT_NAME not found, skipping..."
    fi
done

# Calculate average CLIP score
if [ ${#CLIP_SCORES[@]} -gt 0 ]; then
    SUM=0
    COUNT=${#CLIP_SCORES[@]}

    for SCORE in "${CLIP_SCORES[@]}"; do
        SUM=$(echo "$SUM + $SCORE" | bc -l)
    done

    AVERAGE=$(echo "scale=2; $SUM / $COUNT" | bc -l)

    # Save average to a file
    AVERAGE_FILE="$OUTPUT_FOLDER/average_clip_score.txt"
    echo "Average CLIP Score: $AVERAGE" > "$AVERAGE_FILE"
    echo "Saved average CLIP Score to $AVERAGE_FILE"
else
    echo "No valid scores to calculate average."
fi

echo "All prompts processed."
