_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 41
                - 55
                - 79
            "2":
                - 1
                - 41
                - 55
                - 79
            "3":
                - 13
                - 23
                - 35
                - 55
            "4": 3.9.20
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
